import react,{Component} from "react";


const moviesData = [
    {
     "Title": "The Land Girls", 
     "Us_Gross": 146083, 
     "Worldwide_Gross": 146083, 
     "US_DVD_Sales": null, 
     "Production_Budget": 8000000, 
     "Release_Date": "Jun 12 1998", 
     "MPAA_Rating": "R", 
     "Running_Time_min": null, 
     "Distributor": "Gramercy", 
     "Source": null, 
     "Major_Genre": null, 
     "Creative_Type": null, 
     "Director": "David Leland", 
     "Rotten_Tomatoes_Rating": null, 
     "IMDB_Rating": 6.1, 
     "IMDB_Votes": 1071
    },
    {
     "Title": "First Love, Last Rites", 
     "Us_Gross": 10876, 
     "Worldwide_Gross": 10876, 
     "US_DVD_Sales": null, 
     "Production_Budget": 300000, 
     "Release_Date": "Aug 07 1998", 
     "MPAA_Rating": "R", 
     "Running_Time_min": null, 
     "Distributor": "Strand", 
     "Source": null, 
     "Major_Genre": "Drama", 
     "Creative_Type": null, 
     "Director": "Ian McEwan", 
     "Rotten_Tomatoes_Rating": null, 
     "IMDB_Rating": 6.9, 
     "IMDB_Votes": 207
    },
    {
     "Title": "I Married a Strange Person", 
     "Us_Gross": 203134, 
     "Worldwide_Gross": 203134, 
     "US_DVD_Sales": null, 
     "Production_Budget": 250000, 
     "Release_Date": "Aug 28 1998", 
     "MPAA_Rating": null, 
     "Running_Time_min": null, 
     "Distributor": "Lionsgate", 
     "Source": null, 
     "Major_Genre": "Comedy", 
     "Creative_Type": null, 
     "Director": "Bill Plympton", 
     "Rotten_Tomatoes_Rating": null, 
     "IMDB_Rating": 6.8, 
     "IMDB_Votes": 865
    },
    {
     "Title": "Let's Talk About Sex", 
     "Us_Gross": 373615, 
     "Worldwide_Gross": 373615, 
     "US_DVD_Sales": null, 
     "Production_Budget": 300000, 
     "Release_Date": "Sep 11 1998", 
     "MPAA_Rating": null, 
     "Running_Time_min": null, 
     "Distributor": "Fine Line", 
     "Source": null, "Major_Genre": "Comedy", 
     "Creative_Type": null, 
     "Director": "Tony Cat", 
     "Rotten_Tomatoes_Rating": 13, 
     "IMDB_Rating": null, 
     "IMDB_Votes": null
    },
    {
   "Title":"Back to the Future Part III",
   "Us_Gross":87666629,
   "Worldwide_Gross":243700000,
   "US_DVD_Sales":null,
   "Production_Budget":40000000,
   "Release_Date":"May 24 1990",
   "MPAA_Rating":null,
   "Running_Time_min":null,
   "Distributor":"Universal",
   "Source":"Original Screenplay",
   "Major_Genre":"Adventure",
   "Creative_Type":"Science Fiction",
   "Director":"Robert Zemeckis",
   "Rotten_Tomatoes_Rating":71,
   "IMDB_Rating":7.1,
   "IMDB_Votes":77541
},
{
   "Title":"Ben-Hur",
   "Us_Gross":73000000,
   "Worldwide_Gross":73000000,
   "US_DVD_Sales":null,
   "Production_Budget":15000000,
   "Release_Date":"Nov 18 1959",
   "MPAA_Rating":null,
   "Running_Time_min":null,
   "Distributor":"MGM",
   "Source":"Based on Book/Short Story",
   "Major_Genre":"Adventure",
   "Creative_Type":null,
   "Director":"William Wyler",
   "Rotten_Tomatoes_Rating":91,
   "IMDB_Rating":8.2,
   "IMDB_Votes":58510
}
];
export default moviesData;
